# Generated by Django 5.2.9 on 2025-12-05 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrativo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(max_length=100, unique=True)),
                ("password", models.TextField()),
                ("foto", models.TextField()),
                ("correo", models.TextField(unique=True)),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="administrativo.rol",
                    ),
                ),
            ],
        ),
    ]
